# Generated by Django 3.0.8 on 2021-02-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='times_learned',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.Word')),
            ],
        ),
    ]
