# Generated by Django 3.0.8 on 2021-02-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20210202_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
